twilio/twilio-cli

- package-lock.json
- package.json
- src/commands/project/add.js
- src/commands/project/list.js
- test/commands/project/add.test.js
- test/commands/project/list.test.js
- Adds a region flag to the project topic
> Add project region support

- README.md
Some folks have run into `EACCES` errors trying to globally install npm packages.
> Add setup troubleshooting

- src/base-commands/twilio-api-command.js
- test/base-commands/twilio-api-command.test.js
- Accept varying case command API options and display the lower-case options in the help
- This is to support APIs that only accept a specific case, but don't call that out in their definition
> Support enum flags of varying case

- .github/pull_request_template.md
- README.md
Moved plugin documentation to later in the readme
- 
- 
> Move plugin docs in README

- src/commands/project/add.js
- test/commands/project/add.test.js
- If the user has credential env vars set when adding/updating the default project, they are prompted to continue or cancel
> Prompt user when creating default project with env vars set

- package-lock.json
- package.json
- src/commands/project/add.js
- test/commands/project/add.test.js
- When adding a new project, this change prompts the user for the project name if they did not provide one
> Prompt for project name if not provided when adding a project

- package.json
- src/hooks/init/twilio-api.js
- src/hooks/post-api-plugin/plugin-verification.js
- src/services/messaging/templates.js
- test/hooks/init/twilio-api.test.js
- test/hooks/post-api-plugin/plugin-verification.js.test.js
- If a plugin is installed that contains a command or alias that conflicts with another plugin or the core CLI, a warning is displayed to the user indicating the offending plugin and the command or alias.
> Spit out a warning when plugins have conflicting commands or aliases

- src/base-commands/twilio-api-command.js
- grepping through our API docs shows 26 booleans which default to `true` and 39 which default to `false`
- This is enough to justify support for the `-no-` option for all API boolean params
> Allow the negated option for API command boolean flags

- README.md
- package.json
- src/commands/phone-numbers/list.js
- src/commands/phone-numbers/update.js
- test/commands/phone-numbers/list.test.js
- test/commands/phone-numbers/update.test.js
- Switch the 'incoming-phone-number' topic to 'phone-numbers'
> Switch the 'incoming-phone-number' topic to 'phone-numbers'

- package-lock.json
- package.json
- src/hooks/init/plugin-verification.js
- src/hooks/init/twilio-api.js
- test/hooks/init/plugin-verification.js.test.js
- test/hooks/init/twilio-api.test.js
- Make the API plugin initialization synchronous so future init hook processors will always be run after it completes 
> Make the API plugin init synchronous so other hook processors can be run after

- package.json
The missing `welcome.js` file is causing installation troubles
* [ x] I acknowledge that all my contributions will be made under the project's license
> Include welcome.js in package

- package-lock.json
- package.json
- src/base-commands/twilio-api-command.js
- src/commands/phone-numbers/list.js
- src/commands/phone-numbers/update.js
- src/commands/projects/add.js
- src/hooks/init/buy-phone-number.js
- src/services/resource-helpers/api/v2010/incoming-phone-number.js
- src/services/twilio-api/api-command-runner.js
- src/services/twilio-api/index.js
- test/hooks/init/buy-phone-number.js.test.js
- test/hooks/init/plugin-verification.js.test.js
- test/hooks/init/twilio-api.test.js
- test/services/resource-helpers/api/v2010/incoming-phone-number.test.js
- Adds the `phone-numbers:buy` topic and commands:
```
> twilio phone-numbers:buy
purchase Twilio phone numbers
USAGE
$ twilio phone-numbers:buy:COMMAND
COMMANDS
phone-numbers:buy:local               purchase a local phone number
phone-numbers:buy:machine-to-machine  purchase a machine-to-machine phone number
phone-numbers:buy:mobile              purchase a mobile phone number
phone-numbers:buy:national            purchase a national phone number
phone-numbers:buy:shared-cost         purchase a shared-cost phone number
phone-numbers:buy:toll-free           purchase a toll-free phone number …
```
> Add commands to buy phone numbers

- docs/general_usage.md
- Makes the link to the plugins doc an absolute URL so it will work when hosted on twilio.com/docs
> Make link to plugins doc absolute

- package.json
> Adding keytar as a dependency

- src/base-commands/twilio-api-command.js
- src/services/twilio-api/api-command-runner.js
- test/base-commands/twilio-api-command.test.js
- Adds a hidden `--skip-parameter-validation` flag to API commands
- This aids our automated Tricorder testing since dummy parameter values don't always match the validation criteria
> Add --skip-parameter-validation flag

- README.md
- docs/general_usage.md
- docs/plugins.md
1. The plugins docs have moved to their own page at twilio.com/docs/twilio-cli/plugins
2. The ngrok integration was reworded to focus on the benefit to the user, rather than the technical implementation
3. Added a security warning about the tunnel/proxy
4. Added a final, missing step to plugin authoring
> Documentation improvements

- src/commands/phone-numbers/update.js
- test/commands/phone-numbers/update.test.js
> Handle generic and complex ngrok errors

- .gitignore
- docs/general_usage.md
- Documents known limitations of the Twilio CLI
> Documents known limitations

- src/commands/phone-numbers/update.js
- test/commands/phone-numbers/update.test.js
> Check for empty props when looking for localhost callback flags

- src/base-commands/twilio-api-command.js
- src/services/twilio-api/api-command-runner.js
- src/services/twilio-api/get-flag-config.js
- test/base-commands/twilio-api-command.test.js
- test/hooks/init/twilio-api.test.js
Also adds a warning messages when a command contains conflicting flags/params.
> Add 'target-account-sid' flag for transferring phone numbers

- .travis.yml
When we deploy after a cleanup, one of the dependencies we need gets removed.
> Skip cleanup on deploy

- .travis.yml
travis encrypt added `matrix` 
> Remove matrix

- src/services/twilio-api/api-command-runner.js
- test/base-commands/twilio-api-command.test.js
In the case of 'target-account-sid', it was being overwritten by 'account-sid'
if both flags were provided. 'account-sid' should already be captured by the
path parameter.
> fix: Don't overwrite parameters when building request

- CONTRIBUTING.md
- src/commands/profiles/create.js
- test/commands/profiles/create.test.js
It is difficult to debug when a user pastes their auth token more than once. This PR provides some guidance when we detect a non-standard length auth token.
> feat: sanity check the account SID and auth token when creating profiles

- docs/general_usage.md
> docs: pin a specific version of the Twilio CLI

- package.json
This fixes error on listing plugin listed in oclif/plugin-plugins repo, https://github.com/oclif/plugin-plugins/issues/86:
Before:
```
./bin/run plugins
TypeError: Cannot read property 'dim' of undefined
at Object.<anonymous> (~/code/twilio-cli/node_modules/@oclif/color/lib/index.js:10:86)
at Object.<anonymous> (~/code/twilio-cli/node_modules/@oclif/plugin-plugins/lib/commands/plugins/index.js:3:17)
```
After:
```
./bin/run plugins
@dabblelab/plugin-autopilot 1.0.2
@twilio-labs/plugin-rtc 0.1.4
@twilio-labs/plugin-serverless 1.3.0
@twilio-labs/plugin-watch 2.0.3
```
> fix: added in @oclif/color 0.1.0 dependency

- package-lock.json
- package.json
This is a patch to fix https://github.com/twilio/twilio-cli/issues/187 and is similar to https://github.com/twilio/twilio-cli-core/pull/88. Still working on a more proper fix.
The 'plugin-plugins' module was not loading properly because of some bug in 'tslib-1.12.0'. Users would see the error `TypeError: Plugins is not a constructor` when attempting to install a runtime dependency.
> fix: pin 'tslib' to avoid issues when interacting with plugin-plugins

- src/services/twilio-api/get-topic-name.js
- test/services/twilio-api.test.js
The account create, fetch, list, and update commands were previously under the 'api:core' topic (mixed in with other topics). This change moves the to under their  own 'api:core:accounts' topic.
Before:
```
➜ twilio api:core
resources under api.twilio.com
USAGE
$ twilio api:core:COMMAND
COMMANDS
api:core:addresses                An Address instance resource represents your or your customerâ€™s physical location within a country. Around the world, some
local authorities require the name and address of the user to be on file with Twilio to purchase and own a phone number.
api:core:applications             An Application instance resource represents an application that you have created with Twilio. An application inside of Twilio
is just a set of URLs and other configuration data that tells …
```
> feat: move Twilio (Sub)Account APIs to their own topic

- src/commands/profiles/create.js
Relates to https://github.com/twilio/twilio-cli/issues/196
> fix: don't debug log the API key secret when creating profiles

- package-lock.json
- package.json
- src/services/file-io.js
- test/commands/email/send.test.js
Supplying a file path for an email attachment with a tilde to mean the home directory when using email:send fails. Node.js doesn't support expanding `~` to `os.homedir()` by default, but the untildify package does create a safe way to achieve this.
I worked on this because I tried to send an attachment a number of times with files that definitely existed, but the CLI was telling me they couldn't be found. When I finally used an absolute path, it worked. I'd like to remove that frustration from anyone else that tries.
> feat: Makes file paths with tildes work for email:send

- src/commands/profiles/remove.js
The profile ID is a required arg.
> fix: remove the profile option from the "profiles:remove" command

- src/services/twilio-api/get-action-description.js
- test/services/twilio-api.test.js
https://issues.corp.twilio.com/browse/DI-956
We currently use ga/beta under tags. This PR moves them to a vendor extension instead.
- https://code.hq.twilio.com/twilio/yps/pull/57
- https://github.com/twilio/twilio-cli-core/pull/105
- https://github.com/twilio/twilio-oai/pull/14
> chore: replace tags with vendor extension

- src/hooks/init/twilio-api.js
Related PR: https://github.com/twilio/twilio-cli-core/pull/116
Removes the code that masks the preview domain OpenAPI doc, since it will no longer be rendered in cli-core.
Note: The Travis build will knowingly fail until a new version of @twilio/cli-core is published to npm. This has been tested and passes locally when creating a link to a local version of cli-core in the `package.json`
> chore: remove preview gate

- src/commands/profiles/list.js
- src/commands/profiles/remove.js
Fixes [DI-1475](https://issues.corp.twilio.com/browse/DI-1475)
As we are adding a new JSON object for profiles, the existing code using the profiles object (which is reading the projects array) is being refactored. 
Dependent PR in twilio-cli-core : [Link](https://github.com/twilio/twilio-cli-core/pull/122)
- Tested Unit Tests : [Test Report GIST](https://gist.github.com/onuzbee/4d64268a7927b4b472e6f0c4757057dd)
- Tested profiles usage - create/remove/list manually 
> chore: Refactor profiles usage to projects

- src/services/plugins.js
Recently released a new [plugin for using Twilio Assets from the CLI as part of the Serverless Toolkit](https://github.com/twilio-labs/serverless-toolkit/tree/main/packages/plugin-assets). This adds the plugin to the available plugins list.
> feat: add assets plugin to available plugins

- src/commands/profiles/create.js
- test/commands/profiles/create.test.js
Closes : [DI-1353](https://issues.corp.twilio.com/browse/DI-1353)
Changes in profile Update: While updating the profile using config file instead of the system keychain.
Testing Gist : [Link](https://gist.github.com/ravali-rimmalapudi/7b73d28a58bedebc278491f498e1af9a)
> chore: CLI Profile Update - Using config file instead of the system keychain

- package.json
Updated package.json to point to cli-core release candidate and cli-test new release
> chore - Updated package.json to point to cli-core release candidate and cli-test new release

- .nycrc.json
- .travis.yml
- package.json
- sonar-project.properties
Closes DI-1381. 
Adds sonarcloud configurations. Related PR in `twilio-cli-core` with tested main push: [Link](https://github.com/twilio/twilio-cli-core/pull/136)
> chore: Add sonarcloud configurations

- .github/workflows/docker-release.yml
- .github/workflows/release.yml
Fork docker release workflow to be triggered standalone. 
> fix: Fork out docker release workflow

- Dockerfile
Closes [DII-162](https://issues.corp.twilio.com/browse/DII-162). Tested basic functionality of CLI. 
> fix: Pin node version to 14.18.1 in Dockerfile

- .github/workflows/acceptance-tests.yml
This PR: 
In acceptance tests for homebrew and scoop releases, rather than waiting on the triggering script, it waits on the responsible repos and their workflow scripts. 
> fix: acceptance testing for brew and scoop releases

- src/commands/config/set.js
- test/commands/config/set.test.js
When a user enters invalid arguments to the `config:set` command, the error message mistakenly references an incorrect command name, `configs:set`:
```sh
$ twilio config:set
» No configuration is added to set. Run "twilio configs:set --help" to see how to set a configurations.
$ twilio configs:set --help
›   Error: command configs:set not found
$ twilio config:set --help
update Twilio CLI configurations.
USAGE
$ twilio config:set
...
```
This change corrects that mistake in the error message (along with the corresponding test).
> fix: correct a typo in config:set error messaging

- .github/workflows/acceptance-tests.yml
This PR fixes the acceptance test to test the x64 pkg file. As the runner runs on macos-latest, it [cannot](https://github.com/actions/runner-images/issues/2187) yet test the M1 executable. 
> chore: run acceptance test on macos x64 executable

- .github/workflows/rpmbuild.yml
RPM build failure in CLI release
Removing the gh release create step due to rpm build failure
> fix: Removing the gh release create step due to rpm build failure

- package.json
- src/hooks/init/twilio-api.js
Added support for Safelist query params
> chore: added support for SafeList query params

- .github/workflows/cli-audit.yml
- Makefile
- package.json
- src/hooks/init/twilio-api.js
> chore: upgraded cli-core version and skip healthcheck api

- package.json
Bumping cli-core version after https://github.com/twilio/twilio-cli-core/pull/247
> chore: bump cli-core version

- package-lock.json
- src/services/api-schema/json-validator.js
Certain endpoints allow sending empty value in the string sids. But we are preventing it from cli. Removing that check to allow passing such values. In case of error, we'll show server error and not 4XX. 
> chore: add support to pass empty string params
