twilio/twilio-cli

README.md
- Badge link in `README.md` to npm package 🤓!
=> Badge link to npm package!

README.md, src/commands/project/add.js
- Upstream change in core ([PR #4](https://github.com/twilio/twilio-cli-core/pull/4)) no longer defaults the project flag, so we must do it here
=> Use env vars first for credentials if no project is specified

README.md, VERSIONS.md
- Add versioning link and doc to README
=> Add versioning link and doc to README

src/base-commands/twilio-api-command.js, src/services/twilio-api/api-browser.js, test/base-commands/twilio-api-command.fixtures.js, test/base-commands/twilio-api-command.test.js, test/services/twilio-api.test.js
- Use the default output properties from the API definition
=> Use the default output properties from the API definition

docs/cookbook.md, src/base-commands/twilio-api-command.js, src/hooks/init/twilio-api.js, src/services/twilio-api/api-browser.js, src/services/twilio-api/get-topic-name.js, src/services/twilio-api/index.js, test/base-commands/twilio-api-command.test.js, test/hooks/init/twilio-api.test.js
- Chops 'api:v2010:accounts' down to just 'api:core'
- Moves all API resources to under 'api'
=> Move all API resources to under a single 'api' topic

package.json, src/commands/login.js, welcome.js
- Added a welcome message at the end of the installation process to guide the user on what to do next without RTM
- Added a login alias to expose project:add functionality at the base help level (e.g. twilio help)
=> Improve Getting Started Experience

README.md
- Update readme to reflect changes with use command
=> Update readme to reflect changes with use command

README.md
Added instruction for installing via Homebrew
=> Updated installation instructions, adding Homebrew

README.md, package.json, src/commands/login.js, src/commands/projects/add.js, src/commands/projects/list.js, src/commands/projects/use.js, test/commands/projects/add.test.js, test/commands/projects/list.test.js, test/commands/projects/use.test.js, welcome.js
- Switch the `project` topic to `projects` (plural)
=> Switch the 'project' topic to 'projects'

UPGRADE.md, package-lock.json, package.json
- Update `cli-core` dependency and add upgrade guide for the next release.
=> breaking: Move the config directory to '.twilio-cli'

src/hooks/init/twilio-api.js, src/services/twilio-api/api-browser.js, test/hooks/init/twilio-api.test.js
=> Remove api:preview from the command tree

docs/general_usage.md
=> Fix anchor href for logging messages and serverless naming

CONTRIBUTING.md
=> Additional debugging information

CONTRIBUTING.md, package.json, src/hooks/init/plugin-install.js, test/hooks/init/plugin-install.js.test.js
=> Warn users when installing plugins outside of Twilio and Twilio-Labs

package-lock.json, package.json
* The plugin currently checks once per day.
* The upgrade message can be updated in the package.json settings.
* The update is triggered upon release to the public npm registry.
=> Add plugin-warn-if-update-available plugin

docs/plugins.md
- Add recommendations about naming and help. Specifically warning plugin authors about collisions and making top level help lowercase.
- 
=> Add recommendations about naming and help

README.md
=> Remove pre-release warning

src/commands/feedback.js
Broken redirect to feedback form
- 
- 
=> Update feedback link

src/services/api-schema/json-validator.js
=> fix(chore): Fix error message when exceeding schema max items

docs/general_usage.md, src/commands/login.js, src/commands/profiles/create.js, src/commands/profiles/list.js, src/commands/profiles/remove.js, test/commands/profiles/create.test.js, welcome.js
Change in core: https://github.com/twilio/twilio-cli-core/pull/70
=> Rename 'profiles:add' to 'profiles:create'

.travis.yml
=> fix: travis npm deploy

src/commands/profiles/create.js, test/commands/profiles/create.test.js
=> fix: allow login when no user has no username

package-lock.json, package.json, src/commands/debugger/logs/list.js, test/commands/debugger/logs/list.test.js
=> chore: move the debugger command out of the debugger plugin

src/commands/email/send.js, src/services/file-io.js, test/commands/email/send.test.js
This option avoids an attachment prompt.
=> feat: add '--no-attachment' option to 'email:send'

src/commands/plugins/available.js, src/hooks/command-not-found.js, src/hooks/plugin-install.js, src/services/plugins.js, test/commands/plugins/available.test.js
=> feat: add 'plugins:available' command that lists trusted, uninstalled plugins

package-lock.json, src/commands/phone-numbers/update.js, src/commands/profiles/list.js
We should not use specific colors for coloring text because it could conflict with the terminal's background color.
=> fix: don't get so fancy with the font color scheme

.npmrc
=> feat: block installation via npm when Node.js requirement not met

src/services/twilio-api/api-command-runner.js
`conversations:v1:configuration:fetch` command doesn't have
any parameter, therefore parameters property is not defined in
the OpenAPI spec.
This commit fixes the assumption that all actions have parameters.
Depends on https://github.com/twilio/twilio-cli-core/pull/103
=> fix: commands with actions without parameters

src/commands/profiles/list.js, test/commands/profiles/list.test.js
Closes DI-309 
Indicate whether env vars are being used in `twilio profiles:list`
Walkthrough: 
=> chore: Indicate environment variables being used in profiles:list

package.json
Closes DI-369
Add link to CLI homepage in the help description
=> chore: Updating help description to include the quickstart doc url

docs/general_usage.md
[DEVED-4480](https://issues.corp.twilio.com/browse/DEVED-4480).
=> docs: add test credentials disclaimer

.travis.yml, package-lock.json, package.json, src/services/email-utility.js
=> fix: conform to eslint guidelines

src/commands/profiles/create.js, test/commands/profiles/create.test.js, test/commands/profiles/list.test.js, test/commands/profiles/remove.test.js
Closes : [DI-1350](https://issues.corp.twilio.com/browse/DI-1350)
Dependent PR: [Link](https://github.com/twilio/twilio-cli-core/pull/124) 
Changes in profiles:create to add api keys in config file. 
Testing Gist : [Link](https://gist.github.com/onuzbee/2cfa2477ece0ce39118312428859d99c)
=> chore: Store API Keys in Config File

src/commands/profiles/remove.js, test/commands/profiles/remove.test.js
Closes : [DI-1352](https://issues.corp.twilio.com/browse/DI-1352)
Dependent PR: [Link](https://github.com/twilio/twilio-cli-core/pull/126)
Changes in profiles remove : Check and Use config file before checking system keychain.
Testing Gist : [Link](https://gist.github.com/ravali-rimmalapudi/65e452ba862934fef0684552b2529d31)
=> chore: CLI Profile Remove - Check and Use config file before checking system keychain.

src/commands/profiles/list.js, test/commands/profiles/list.test.js
Closes : [DI-1510](https://issues.corp.twilio.com/browse/DI-1510)
Changes in profiles list: While listing the profiles include the config profiles.
Testing Gist : [Link](https://gist.github.com/ravali-rimmalapudi/c9ebf5d242264f7cf475171c74dc23d4)
=> chore: Update profiles list

package.json, src/commands/profiles/port.js, test/commands/profiles/port.test.js
Closes [DI-1356](https://issues.corp.twilio.com/browse/DI-1356)
Testing Gist: [Link](https://gist.github.com/onuzbee/6eb5d956694b460dcc9640da2b016b54)
Adds profiles:port functionality. 
=> chore: Add profiles:port

src/commands/profiles/create.js, src/commands/profiles/list.js, test/commands/phone-numbers/update.test.js, test/commands/profiles/list.test.js, test/commands/profiles/remove.test.js
Closes : [DI-1479](https://issues.corp.twilio.com/browse/DI-1479)
Dependent PR: [CLI-CORE](https://github.com/twilio/twilio-cli-core/pull/131), [CLI-TEST](https://github.com/twilio/twilio-cli-test/pull/8)
Changes in active profile: Throwing the alert when active profile is NULL and no environment variable is set in case of any command that requires API keys.
Testing Gist : [Link](https://gist.github.com/ravali-rimmalapudi/dc9c998fd1445c9784d43faa2f4f4e04)
=> chore: Throw alert when active profile is not set

package-lock.json, package.json
Closes : [DI-36](https://issues.corp.twilio.com/browse/DI-36)
The default help output just lumps topics and commands under one heading called "COMMANDS". This was confusing to a few people. We are using @oclif/plugin-help to provide the help output. Since this change is available in the plugin for version 3.0.0 and above. Updating the version for the plugin to get this change.  
=> chore: updating plugin-help version

src/services/post-install-utility.js, test/services/post-install-utility.test.js, welcome.js
[DI-421](https://issues.corp.twilio.com/browse/DI-421)
[DI-1355](https://issues.corp.twilio.com/browse/DI-1355)
Testing Gist : [Link](https://gist.github.com/onuzbee/721995d7152580e4967eb14cbae89e37)
Changes display warning mechanism to be based on user profiles.
Screenshots: 
=> chore: change post install messaging behaviour

package.json, src/commands/config/list.js, src/commands/config/set.js, src/services/config-utility.js, test/commands/config/list.test.js, test/commands/config/set.test.js
Closes : [DI-705](https://issues.corp.twilio.com/browse/DI-705)
Adding the twilio config command to list/set the twilio edge configuration 
Testing Gist : [Link](https://gist.github.com/ravali-rimmalapudi/530bd9f52809e7863622fdbf682c63de)
=> feat: Added twilio config to list/set edge configuration

package.json, src/hooks/postrun/plugin-postrun.js, src/services/post-install-utility.js, test/hooks/postrun/plugin-postrun.test.js, test/services/post-install-utility.test.js
Closes : 
[DI-754](https://issues.corp.twilio.com/browse/DII-5)
[DII-5](https://issues.corp.twilio.com/browse/DII-5)
Screenshot for [DI-754](https://issues.corp.twilio.com/browse/DII-5):
When plugins:update is run: 
When any other command is run: 
Screenshot for [DII-5](https://issues.corp.twilio.com/browse/DII-5):
When autocomplete is run without the shell:
When autocomplete is run with the shell:
=> chore: Fix autocomplete bugs

.travis.yml
Added the condition to deploy only specific regex matching tags.
=> fix: Added the condition to check the tag regex

test/base-commands/twilio-api-command.test.js
Currently twilio cli build is failing due to latest cli-core changes, this PR will fix that
=> fix: Fixing failing test on twilio-cli

package.json, src/hooks/plugin-install.js, src/hooks/postrun/plugin-postrun.js, src/hooks/prerun/install-prerun.js, src/services/post-install-utility.js, test/hooks/plugin-install.test.js, test/hooks/postrun/plugin-postrun.test.js, test/hooks/prerun/install-prerun.test.js
Closes  [DII-40](https://issues.corp.twilio.com/browse/DII-40)
Also contains a minor change for  [DI754](https://issues.corp.twilio.com/browse/DI-754)
Screenshot for:
Alert asking the user to update using the 'twilio update' command when a new update is available:
[DII-40](https://issues.corp.twilio.com/browse/DII-40)
Ocif doc: https://oclif.io/docs/releasing.html#autoupdater
Updating using the 'twilio update' command:
(The cli update fails as the installation was npm based. : https://github.com/oclif/plugin-update/issues/49 ) 
No autoupdate warning when the update fails: 
Autoupdate waring for when we install new plugins: 
Screenshot for: [DI754](https://issues.corp.twilio.com/browse/DI-754)
If you have questions, please file a [support …
=> feature: Twilio update

src/base-commands/twilio-api-command.js, src/hooks/init/twilio-api.js, src/services/api-doc-mapping.json, src/services/twilio-api/get-help-doc-link.js, src/services/twilio-api/index.js, src/services/twilio-help/twilio-command-help.js, test/base-commands/twilio-api-command.test.js, test/services/api-doc-mapping-test.json, test/services/twilio-api.test.js, test/services/twilio-help/twilio-help-doc.test.js
This PR:
Includes "MORE INFO" section which has the API help doc link reference, when `--help` option is enabled. All API help docs aren't available, so there's an explicit mapping of the available paths which is used to generate the reference urls.
[Testing Gist](https://gist.github.com/shrutiburman/20c5923f5c8d73309087a8b189797815)
Screenshots:
=> feat: link to our API docs when you --help

src/services/twilio-help/twilio-command-help.js
Added missing stripAnsi require statement
=> fix: Added missing require statement

.travis.yml, CHANGES.md, package-lock.json, package.json, src/services/twilio-help/twilio-command-help.js
=> Merging changes from main

.github/workflows/release.yml
Closes : [DII-80](https://issues.corp.twilio.com/browse/DII-80)
=> chore: Add docker workflow to github actions

.github/workflows/oclif-release.yml, .github/workflows/release.yml, .releaserc.json
Closes:[[DII-108](https://issues.corp.twilio.com/browse/DII-108)]
Added github action workflow for oclif dev pack and update homebrew
Testing Gist: [[Link](https://gist.github.com/ravali-rimmalapudi/7c55f101050a8aa0aba63beadbfbcafc)]
=> feat: Added github actions for publish to s3 and trigger homebrew release

src/services/twilio-api/get-flag-config.js, test/services/twilio-api.test.js
This PR: 
Uses the hyperlink-utility (from [DII-47](https://issues.corp.twilio.com/browse/DII-47)) to convert long markdowns in description. 
This works only with terminals that [support](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) hyperlinks. 
[Build log](https://app.travis-ci.com/github/twilio/twilio-cli/jobs/537973450)
Screenshots: 
Supported Terminals (iTerm): 
Unsupported Terminals (Mac Terminal):
- [] I have made a material change to the repo (functionality, testing, spelling, grammar)
=> Changes to make markdowns into hyperlinks

.releaserc.json
Workaround for the semantic github plugin issue.
=> Fixing the semantic github issue

test/services/twilio-api.test.js
=> fix: Hide tests showing non-deterministic behaviour

.github/workflows/oclif-release.yml
=> fix: Add aws session token

src/services/twilio-api/get-flag-config.js
=> fix: replaceAll bug

.github/workflows/release.yml
Closes [DII-134](https://issues.corp.twilio.com/browse/DII-134): Fixing the protected branch issue.
Workflow Runs: [Failed Run](https://github.com/ravali-rimmalapudi/twilio-cli-core/runs/3728882137?check_suite_focus=true#step:6:66), [Passed Run](https://github.com/ravali-rimmalapudi/twilio-cli-core/runs/3729045192?check_suite_focus=true#step:6:64)
BranchProtection: [Enabled](https://github.com/ravali-rimmalapudi/twilio-cli-core/settings/branches)
=> Fixing the branch protection issue.

.github/scripts/update-platform-executables.js, .github/workflows/platform-executables.yml, .github/workflows/release.yml
Added platform executables generation from Github actions.
=> Added Github actions for windows, linux and mac platform executables

.github/scripts/trigger-workflow.js, .github/scripts/update-release.js, .github/workflows/release.yml
=> chore:Replaced the community actions with the scripts

.github/scripts/commit-api-spec-change-log.sh, .github/workflows/oclif-release.yml, .github/workflows/release.yml, .releaserc.json
1. Updated OAI commit not to include in release notes and changeLog
2. Updated the yml with proper names
Closes: [DII-133](https://issues.corp.twilio.com/browse/DII-133)
Dependent PR: [CLI-CORE](https://github.com/twilio/twilio-cli-core/pull/161)
=> fix: Added the following changes:

package.json
Fix security vulnerability: https://github.com/twilio/twilio-cli/security/dependabot/package-lock.json/ansi-regex/open
=> fix: Resolve security vulnerability for ansi-regex

.github/workflows/oclif-release.yml, githooks/pre-commit
Add xz compression for tarballs. 
Sample run `npx oclif-dev pack --xz`:
Note: This PR also removes git pre-run hook due to known audit issues with the repo. 
```
oclif-dev: packing tarball from ./tmp/twilio to ./dist/twilio-v2.32.1/twilio-v2.32.1.tar.gz
tar: Failed to set default locale
oclif-dev: packing tarball from ./tmp/twilio to ./dist/twilio-v2.32.1/twilio-v2.32.1.tar.xz
tar: Failed to set default locale
oclif-dev: building target twilio-v2.32.1-linux-x64.tar.gz
oclif-dev: packing tarball from ./tmp/linux-x64/twilio to ./dist/twilio-v2.32.1/twilio-v2.32.1-linux-x64.tar.gz
tar: Failed to set default locale
oclif-dev: packing tarball from ./tmp/linux-x64/twilio to ./dist/twilio-v2.32.1/twilio-v2.32.1-linux-x64.tar.xz
tar: Failed to set default locale
oclif-dev: building target …
```
=> chore: Add xz compression for tarballs

.github/actions/build-rpm/Dockerfile
Specifying the version of node for rpm to fix [this](https://github.com/twilio/twilio-cli/runs/4101046584?check_suite_focus=true)
=> fix: specifying the version of node for rpm

.github/actions/build-rpm/Dockerfile
The version of node was hardcoded and this needs to be reverted. 
=> fix: reverting changes for the RPM build

src/services/hyperlink-utility.js
Fixes[ DII-132](https://issues.corp.twilio.com/browse/DII-132)
This PR:
Solves the [indentation issue](https://github.com/jamestalmage/supports-hyperlinks/issues/13) introduced via dependency supports-hyperlink (to convert markdowns into url). 
For Ubuntu terminals, the markdown conversion is disabled till the time issue gets resolved by lib owners for node 10.x .
Alternative dependencies aren't compliant with node 10.x. 
Before:
After: 
=> fix: Disable hyperlinks in Ubuntu for indentation issue

.github/actions/build-rpm/Dockerfile, .github/workflows/cli-test.yml, .github/workflows/oclif-release.yml, .github/workflows/platform-executables.yml, .github/workflows/release.yml, .github/workflows/rpmbuild.yml
DII-200
Made changes to release process to fetch the latest dependencies for the release.
Test run https://github.com/kridai/twilio-cli/runs/4210117010?check_suite_focus=true
=> fix: updating release steps to fetch latest dependencies

.github/scripts/pack-debian-apt.js, .github/scripts/pack-debian.js, .github/workflows/apt-release.yml
Closes : https://issues.corp.twilio.com/browse/DII-155
Following changes are added
Packaging the debian binary file, along with the different scripts (control, postinstall)
Configured the changes for setting up a private debian repo for apt
Publishing the apt repo to AWS S3
Test run : https://github.com/kridai/twilio-cli/runs/4011298325?check_suite_focus=true
=> feat: adding workflow for apt release

.github/workflows/oclif-release.yml
fix: Updating formula for the release feature branch
=> fix: Updating formula for the release feature branch

package.json
Adds xz flag to generage SHA and push xz tarballs to S3 with every `npx oclif-dev publish`
=> chore: Add xz flag for S3 update

.github/workflows/platform-executables.yml, .github/workflows/release.yml, .github/workflows/windows-executable-release.yml
Closes: https://issues.corp.twilio.com/browse/DII-146
adding windows package signing configurations for github actions
Successful run link: https://github.com/kridai/twilio-cli/actions/runs/1489163412
Failure /canceled case: https://github.com/kridai/twilio-cli/runs/4283768999?check_suite_focus=true
=> feat: adding windows package signing configurations

package.json
=> fix: remove ngrok from force dependencies

.github/workflows/oclif-release.yml, .github/workflows/slack-notification.yml
Jira: https://issues.corp.twilio.com/browse/DII-217
=> chore: Trigger scoop repo workflow through release

.github/workflows/release.yml, .github/workflows/windows-executable-release.yml
tested run on workflow_run (automatic): https://github.com/kridai/twilio-cli/actions/runs/1529571737
tested run on workflow_dispatch (manual): https://github.com/kridai/twilio-cli/actions/runs/1529568188
=> fix: updating windows release workflow

.github/scripts/trigger-and-wait.sh
Fixes mismatched workflow tracking: https://github.com/twilio/twilio-cli/runs/4393265395?check_suite_focus=true#step:3:26
=> fix: Add delay before checking latest workflow id

src/base-commands/twilio-api-command.js, src/commands/debugger/logs/list.js, src/commands/phone-numbers/list.js, src/commands/profiles/list.js, test/base-commands/twilio-api-command.test.js, test/commands/debugger/logs/list.test.js, test/commands/phone-numbers/list.test.js, test/commands/profiles/list.test.js
Closes: [DII-12](https://issues.corp.twilio.com/browse/DII-12)
=> Add flag no header for fetch and list commands.

.github/workflows/release.yml
Semantic release step failed during our last release process and failure happened when It was trying to reading current tag version and returned NOTAGNAME and INVALIDTAGNAME error codes. 
In this fix I changed the command from npx to npm bin command which worked. I don't the reason why later one worked as compare to former one.  I have rasied the issue on semantic-release repo (https://github.com/semantic-release/semantic-release/issues/2297) to know more about it.
=> chore: change semantic-release command in github action steps

.github/scripts/pack_macos.sh, .github/workflows/macos-executable-release.yml, .github/workflows/release.yml, package.json
Closes: DII-123
Get the application certificate setup and finish the notarization for macOS binary. Once we verify the executable is signed and verified, add the steps into Github Actions
Run: 
Note, since keytar dependency is still there, currently the notarization is failing.
Test run: https://github.com/kridai/twilio-cli/runs/4405540530?check_suite_focus=true
=> feat: added notarization changes

package.json
update some of oclif vulnerabilities which will not impact current implementation of twilio-cli
=> chore: update vulnerable dependencies

package.json
Plugin-help rolled out a major version recently which is seems to be breaking for us.
=> fix: Pin plugin-help to 3.2.17

.github/scripts/trigger-and-wait.sh
=> fix: Poll workflow status for Scoop/HomeBrew

package.json
https://issues.corp.twilio.com/browse/DII-243
Screenshot: 
=> fix: Run npm audit for only production dependencies

.github/workflows/macos-executable-release.yml
updated macos release to upload binary even if notarization fails
Added if always() condition to upload binary step, this will ensure the step is run even if previous steps fail. We could also have updated the exit code of the script (pack_macos.sh) to pass in case of failure but wanted more visibility of the failure in the run logs. 
Test run: https://github.com/kridai/twilio-cli/actions/runs/1586232574 , here the pack-macos step fails but we still upload the binary to release
=> chore: update macos release workflow

LICENSE
=> chore: Update License

package.json
Bumping `@oclif/color` - Pin pointing base with resolved security vulnerabilities: https://github.com/oclif/color/releases/tag/v1.0.1
=> chore: Bump dependency

.github/scripts/metrics/npm_metrics.py, .github/workflows/npm-download-metrics.yml
Changing the time of the cron job, as the npm API didn't have the values at 9am IST. 
=> Changing the time of the cron job

src/hooks/prerun/install-prerun.js, test/hooks/prerun/install-prerun.test.js
Jira: https://issues.corp.twilio.com/browse/DII-152
=> chore: Add twilio docs link for twilio update

package.json
Jira: https://issues.corp.twilio.com/browse/DII-145
=> chore: Add link to docs with update notification

.github/workflows/platform-executables-acceptance-tests.yml
Correct the terminology in testing workflow
=> fix: Correct terminology in testing workflow

src/commands/profiles/remove.js, test/commands/profiles/remove.test.js
Fixes: https://github.com/twilio/twilio-cli/issues/375
=> fix: Fix profiles remove with environment variables set

test/base-commands/twilio-api-command.test.js
DII-99 introduced a bug in the test, this PR fixes that
=> fix: fix failing test

.github/workflows/platform-executables-acceptance-tests.yml
Segregate platform acceptance test single job into parallel jobs for oclif, macos, windows and debian platform. [DII-305](https://issues.corp.twilio.com/browse/DII-305)
=> chore: segregate single platform acceptance workflow

.github/workflows/cli-test.yml
=> chore: Add back sonar scan

.github/workflows/draft-release.yml
Since Github Actions can only recognize workflows that are on main/ default branch,
adding this dummy workflow file in main to be able to trigger from `draft-release-branch`.
[Reference](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#about-workflow-events)
=> test: Create draft-release.yml to trigger workflow

.github/workflows/debian-draft-executable-release.yml, .github/workflows/draft-release.yml, .github/workflows/platform-executables-acceptance-tests.yml, .github/workflows/windows-executable-draft-release.yml
=> test: Dummy draft workflow

.github/scripts/pack_macos.sh, .github/workflows/macos-executable-release.yml, .github/workflows/oclif-release.yml
Fixes issues encountered during draft release run. 
This PR solves: 
1. Home-brew release sha was empty in the release created. 
Runs : [Oclif release](https://github.com/shrutiburman/twilio-cli/runs/5125375638?check_suite_focus=true#step:5:6) -> [Homebrew release](https://github.com/shrutiburman/homebrew-brew/commit/d35a346b9b5c8b58e0f9695d1f8806e77a8db02e)
2. macos executable wasn't released because of default file name convention. 
Runs: [macos executable filename format change](https://github.com/shrutiburman/twilio-cli/runs/5123615599?check_suite_focus=true#step:3:60)
=> fix: fixing issues from draft release run

.github/actions/build-rpm/Dockerfile, .github/rpm/twilio.spec
Fixed failing RPM build. 
- Previously we were using `centos:latest` tag in Dockerfile, This was picking up centos8. Centos has shifted focus towards  supporting centos stream. More on this [here](https://www.centos.org/cl-vs-cs/). Since centos is updating the centos stream image found [here](https://wiki.centos.org/FAQ/CentOSStream#What_artifacts_are_built.3F). Pulling it in docker file
- The sym linking for twilio wasn't working for this version, so updated twilio.spec file.
- Added the postinstall script which was missing
Testing
- Local : logs https://gist.github.com/kridai/7cfa368fcf0b782dda7ef1a4709aaecd
- action: https://github.com/kridai/twilio-cli/runs/5142627518?check_suite_focus=true
- generated package: https://github.com/kridai/twilio-cli/releases/tag/3.1.0
If you have …
=> fix: fix for failing rpm build

.github/scripts/create-fork-pipeline-changes.js, .github/scripts/pack_macos.sh, .github/workflows/macos-executable-release.yml, .github/workflows/oclif-release.yml, .github/workflows/platform-executables-acceptance-tests.yml, .github/workflows/release.yml, .github/workflows/windows-executable-release.yml, Makefile
Enable developers to run workflow pipeline on fork main repo for testing [DII-314](https://issues.corp.twilio.com/browse/DII-314)
=> Enable developer to run pipeline on fork repo for testing

.github/workflows/acceptance-tests.yml, .github/workflows/platform-executables-acceptance-tests.yml
This PR:
Verifies scoop installation on a windows box, after the release has completed. 
[Workflow run](https://github.com/shrutiburman/twilio-cli/runs/5196305927?check_suite_focus=true)
=> fix: Added Scoop acceptance testing after release

.github/scripts/pack-debian-apt.js, .github/workflows/acceptance-tests.yml, .github/workflows/apt-release.yml
Closes: DII-324
This PR takes care of supporting earlier versions for apt, this will help us provide support to downgrade twilio cli to earlier versions for apt package manager.
Test runs: https://github.com/kridai/twilio-cli/actions/runs/1879650183
Acceptance test: https://github.com/kridai/twilio-cli/runs/5283706198?check_suite_focus=true
=> chore: update support for earlier versions in apt

README.md, src/commands/debugger/logs/list.js, src/commands/feedback.js, test/commands/feedback.test.js
Acceptance criteria :
User is able to find the touchpoint for feedback form
User is redirected to the feedback form by clicking on the link via feedback command or the hyperlink on the touchpoints
User is able to understand  and answer the questions in the feedback form
User is informed about the redirection to feedback form
User is informed /is able to easily identify the mandatory fields 
User is informed that the form is successfully submitted on submission
In case of errors in submission user is informed of the same and reason for error
The user data is captured and available for analysis
The copy is changed appropriately in all touch points
README file to view the changes: https://github.com/sr010/twilio-cli/tree/CLI-Feedback
The NPM touchpoint will reflect the same README once we …
=> Changing the url

.github/workflows/acceptance-tests.yml, .github/workflows/cli-audit.yml, .github/workflows/cli-test-npm.yml, .github/workflows/cli-test.yml, .github/workflows/debian-draft-executable-release.yml, .github/workflows/draft-release.yml, .github/workflows/release.yml, .github/workflows/windows-executable-draft-release.yml
https://issues.corp.twilio.com/browse/DII-320
=> chore: Add nodev12 support 

.github/workflows/acceptance-tests.yml
fix acceptance test failure for apt downgrade. current failure logs : 
https://github.com/twilio/twilio-cli/runs/5314678893?check_suite_focus=true
local run : <img width="1349" alt="Screenshot 2022-03-10 at 7 11 21 AM" src="https://user-images.githubusercontent.com/16255022/157570419-f1317dcd-f55f-4cd0-b08e-b79bbed7be6e.png">
=> chore: fix apt acceptance test failure

src/services/api-doc-mapping.json, test/base-commands/twilio-api-command.test.js, test/services/api-doc-mapping-test.json, test/services/twilio-api.test.js
Update the doc mapping file with correct links. It looks like we overwrote only the command help for providing doc links and not the help for topics and subtopics, so only when the user uses the help for the complete command we give the doc link. Updated the correct doc links for that and also for topics if we want to overwrite help for those in the future.
=> fix: Update doc links

.github/workflows/acceptance-tests.yml
Fixes: https://issues.corp.twilio.com/browse/DII-350
=> fix: Fix scoop installation failures

.github/workflows/cli-test-docker.yml
=> fix: Add input owner for docker test

.github/workflows/cli-test.yml
Don't run multiple times and don't attempt to run for forks.
=> fix: update the condition for running sonar scanner

.github/workflows/acceptance-tests.yml, .github/workflows/cli-test-docker.yml
A short description of what this PR does: 
Fixes the acceptance testing workflow errors from previous release. 
=> fix: acceptance workflow failures fix

src/services/plugins.js
Adds the dev phone to the list of plugin commands
=> chore: add dev phone to plugin commands

package.json
This PR:
Introduces [plugin version](https://www.npmjs.com/package/@oclif/plugin-version) to have more detailed view of version. 
Note: This doesn't work "beautifully" in Oclif v1 (current CLI version) because the [formatting logic](https://github.com/oclif/plugin-version/blob/47d7105a4bd36f8bed8d4772485c4f5eef0fdacd/src/commands/version.ts#L1) is build using components of Oclif V2. 
Currently, this change doesn't block anything and looks like this: 
With Oclif v2 enabled, it'd look like this: 
- [] I have added tests that prove my fix is effective or that my feature works
=> feat: Enabling plugin-version

.github/workflows/acceptance-tests.yml, .github/workflows/audit-check-job.yml, .github/workflows/cli-audit.yml, .github/workflows/cli-test-npm.yml, .github/workflows/cli-test.yml, .github/workflows/draft-release.yml, .github/workflows/release.yml, README.md, package.json
Created cronjob to check NPM audit vulnerabilities which runs every night for prod dependencies and weekly for dev dependencies and sends an alert in case of open vulnerabilities.
For change verification : https://github.com/isha689/twilio-cli-core/actions
=> feat: added audit cronjob

package.json, src/commands/config/set.js, src/commands/debugger/logs/list.js, src/commands/phone-numbers/update.js, src/commands/profiles/create.js, src/hooks/init/buy-phone-number.js, src/hooks/init/twilio-api.js, src/index.js
This PR:
- Introduces fundamental changes required to support oclif v2 in cli.
- Also, removes dev-cli dependency, as its now a part of oclif/core ([here](https://oclif.io/blog/2022/01/12/announcing-oclif-v2#compatibility-matrix)).
- Pins twilio-cli-core version to ^7.0.0, which has oclif v2 changes. 
[Testing Gist](https://gist.github.com/shrutiburman/e9288a1c396ff77f9282df7aac8693b1)
=> chore: removed oclif old dependencies and dev-cli dependency

package.json
=> fix: remove cli-ux dependency

.github/scripts/pack_macos.sh
Fixing the failing macos workflow
Test run : https://github.com/kridai/twilio-cli/runs/7986974901?check_suite_focus=true
=> chore: update macos failing script

.github/scripts/pack-debian-apt.js
updated apt workflow to prevent duplicate version release
test run: https://github.com/kridai/twilio-cli/runs/7988041820?check_suite_focus=true
=> chore: update apt workflow

bin/run, package-lock.json, package.json, src/services/twilio-help/custom-help.js, src/services/twilio-help/twilio-command-help.js, test/services/twilio-help/twilio-help.test.js
Also, verifies [DII-496](https://issues.corp.twilio.com/browse/DII-496)
This PR:
Refactors the plugin-help original implementation to 1. separate out optional and required flags 2. hyperlinks to the documentation for each cmd. 
Example of a cmd which only has optional flags: 
Example of a cmd which has required & optional flags: 
=> chore: refactor plugin-help implementation

.github/workflows/apt-release.yml, .github/workflows/draft-release.yml, .github/workflows/release.yml, .github/workflows/rpmbuild.yml, .github/workflows/windows-executable-release.yml
=> Sync with main

bin/dev, bin/dev.cmd, bin/run, package.json, src/hooks/init/twilio-api.js, test/hooks/init/twilio-api.test.js, tsconfig.json
- Add oclif core bin files
- Dev binary has been introduced by oclif core and It requires typescript
- space topic separator has been introduced
=> fix: add space topic separator

package.json
Also merge: https://github.com/twilio/twilio-cli-core/pull/214
Autocomplete:
Plugins: 
=> Updating @oclif plugins version 

.github/scripts/pack_macos.sh, .github/workflows/macos-executable-release.yml, .github/workflows/windows-executable-release.yml
[Errored workflow](https://github.com/twilio/twilio-cli/actions/runs/3080239164/jobs/4977356702#step:3:234)
[Sample Run](https://github.com/shrutiburman/twilio-cli/actions/runs/3082017013/jobs/4981221132)
=> chore: macos workflow error fix

.github/workflows/oclif-release.yml
The darwin-arm64 files were not being generated due to which `twilio update` cmd was erroring out on M1 chips. Resolved the issue by specifying targets for the oclif-dev pack.
The buckets have to be updated to reflect the changes, which can be done as part of migrating from aws s3 buckets to github repo.
Currently tested in a personal repository: https://github.com/isha689/test, release a 5.1.2 version 
`twilio update` working fine now
=> fix: specifying targets for oclif-dev pack to get missing darwin-arm64 files

.github/workflows/close-stale-issues.yml
**Feat:** Mark old issues as stale and then close after 30 days of inactivity. 
**Exemption:** All issues that have the label [triage queue](https://github.com/twilio/twilio-cli/labels/triage%20queue) will not be picked up. Community enhancements or feature requests received come under this category.
This label should be added to keep the issue from getting stale/closed.
Workflow to mark older issues as stale and after 30 days of being in stale state, the issues are closed automatically. 
Workflow has 2 jobs: 
**1. Close stale issues** : 
- Runs every 10th minute. 
- From given start date, marks every issue `stale` that has been inactive for the past 30 days. 
- From the given start date, `closes` every issue that has been marked `stale` for the past 30 days. 
**2. stale-legacy**:
- Does …
=> ci: mark & close stale issues automatically

.github/scripts/pack-debian-apt.js
This PR:
Adds support for rc tagged releases in apt. 
[Workflow run](https://github.com/shrutiburman/twilio-cli/actions/runs/3831270328/jobs/6520192437) with version `5.0.0-rc.0`
[Workflow run](https://github.com/shrutiburman/twilio-cli/actions/runs/3831339196/jobs/6520341942) with stable release. `5.0.1` 
=> feat: enable rc support in apt releases

.github/scripts/pack_macos.sh
This reverts commit 7d630500b81f49f7287df70fdac3e2f1a4ede8fb.
Reverting removing oclif pack command
Reverting removing oclif pack command
=> Revert removal of oclif command

.github/workflows/macos-executable-release.yml, .github/workflows/release.yml
[DII-540](https://issues.corp.twilio.com/browse/DII-540) Platform exec for rc : macOs pkg
Adding steps to run mac os workflow for release candidates
=> feat: Adding steps to run mac os workflow for release candidates

.github/workflows/debian-executable-release.yml
[DII-539](https://issues.corp.twilio.com/browse/DII-539) Platform exec for rc : deb
Enable steps for rc release for deb in twilio-cli
=> feat: Enable rc workflow for debian

.github/workflows/debian-executable-release.yml
[DII-832](https://issues.corp.twilio.com/browse/DII-832) Publish armel and amd artifacts to github for debian
Enabling upload of deb files for armel for rc branch
=> feat: Enabling upload of deb files for armel for rc branch

.github/workflows/debian-executable-release.yml
[DII-832](https://issues.corp.twilio.com/browse/DII-832) Publish armel and amd artifacts to github for debian
Upload armel deb files during debian release
=> feat: Upload armel deb files during debian release

.github/workflows/acceptance-tests.yml, .github/workflows/apt-release.yml, .github/workflows/audit-check-job.yml, .github/workflows/cli-audit.yml, .github/workflows/cli-test-docker.yml, .github/workflows/cli-test-npm.yml, .github/workflows/cli-test.yml, .github/workflows/close-stale-issues.yml, .github/workflows/create-draft-branch.yml, .github/workflows/debian-executable-release.yml, .github/workflows/docker-release.yml, .github/workflows/github-download-metrics.yml, .github/workflows/macos-executable-release.yml, .github/workflows/oclif-release.yml, .github/workflows/release-token-validation.yml, .github/workflows/release.yml, .github/workflows/rpmbuild.yml, .github/workflows/slack-notification.yml, .github/workflows/windows-executable-release.yml
1. Added branch name to workflow
2. Added changes needed for homebrew release
3. Removed unnecessary flags.
=> chore: added branch name to workflow run name

.github/workflows/acceptance-tests.yml
Changed the deb image name.
Test including only for amd64 image
This PR fixes issue:
https://github.com/twilio/twilio-cli/actions/runs/4131698959/jobs/7139589602
=> fix: modify image name in debian acceptance test

package.json
=> chore: twilio-node version update

.github/workflows/close-stale-issues.yml
=> chore: correct workflow run name

.github/workflows/debian-draft-executable-release.yml, .github/workflows/debian-executable-release.yml, .github/workflows/draft-release.yml, .github/workflows/release.yml
Release was failing because of npm bin at semantic release step.
https://github.com/twilio/twilio-cli-core/actions/runs/4249713380/jobs/7390157614
=> fix: using npx instead of npm bin

package.json
Issue:
notarization failing for ngrok for macos package
https://github.com/twilio/twilio-cli/actions/runs/4251750067/jobs/7395256704#step:3:227
Fix:
upgraded ngrok version to 4.3.3
Requesting @kridai @shrutiburman to look into this to check if ngrok is upgraded, will there be an impact.
Below is the success of notarization in forked repo.
https://github.com/sbansla/twilio-cli/actions/runs/4289266006/jobs/7472131383#step:3:221
=> upgraded ngrok version

.github/workflows/apt-release.yml, .github/workflows/debian-executable-release.yml, .github/workflows/oclif-release.yml, .github/workflows/rpmbuild.yml, .github/workflows/windows-executable-release.yml
Changing default version to 16 for all platforms
=> fix: using node 16 versions for all releases

.github/workflows/acceptance-tests.yml, .github/workflows/apt-release.yml, .github/workflows/debian-executable-release.yml, .github/workflows/docker-release.yml, .github/workflows/macos-executable-release.yml, .github/workflows/oclif-release.yml, .github/workflows/release.yml, .github/workflows/rpmbuild.yml, .github/workflows/slack-notification.yml, .github/workflows/windows-executable-release.yml
[DII-542](https://issues.corp.twilio.com/browse/DII-542) Slack notifs for release-candidate branch
Enabling slack notifications only when triggered from main branch, and not when triggered from rc branch
=> feat: Enabling slack notifications only when triggered from main branch

.github/workflows/audit-check-job.yml
[DII-902](https://issues.corp.twilio.com/browse/DII-902) npm audit checks failing for twilio-cli in node v14.x
npm audit checks failing for twilio-cli in node v14.x. To fix this issue running make install after setup of node
=> fix: Swapping make install to be run after setup of node

.github/workflows/cli-audit.yml
Npm audit failures in PRs
[Swapping make install step to run after node setup in npm audit job](https://github.com/twilio/twilio-cli/pull/520#top)
=> fix: Swapping make install step to run after node setup in npm audit job

package-lock.json, package.json
[DII-972](https://issues.corp.twilio.com/browse/DII-972) Fix vulnerabilities in twilio-cli 
Fix vulnerabilities in twilio-cli 
=> fix: Fix vulnerabilities in twilio-cli

Dockerfile
=> fix: Update Dockerfile base image

Dockerfile
Update node version to 18
Update node version to 18
=> fix: Update node version to 18

.github/workflows/oclif-release.yml, Dockerfile
=> fix: Update Dockerfile for fixing the release failure

.github/workflows/apt-release.yml, .github/workflows/debian-executable-release.yml, .github/workflows/macos-executable-release.yml, .github/workflows/oclif-release.yml, .github/workflows/rpmbuild.yml, .github/workflows/windows-executable-release.yml
Using runner image node version
=> chore: using runner image node version

package-lock.json, test/hooks/init/twilio-api.test.js
=> fix: fix preview testcase

package.json
=> cli-core version modified

.github/scripts/update-change-log.js, CHANGES.md
If new change set is added to changes.md file, It won't append new line. Thus making previous commit indentation incorrect.
For example: [changes.md](https://github.com/twilio/twilio-cli/blob/main/CHANGES.md#:~:text=behind%20a%20beta_feature%23%23-,5.13.0%20(2023%2D08%2D24),-%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%2D%5CnApi%5Cn)
=> chore: corrected changes.md identation

.github/scripts/update-platform-executables.js, package.json
Some changes were introduced in the way github actions is used since v3. Earlier it was used like [this](https://www.npmjs.com/package/@actions/github/v/2.2.0?activeTab=readme#usage).  Now it is to be used [this](https://www.npmjs.com/package/@actions/github/v/6.0.0?activeTab=readme#usage) way. This version upgrade was done due to a security vulnerability. 
=> chore: changes for upgrading to actions/github 6.0.0

.github/actions/build-rpm/Dockerfile
Referring to this [comment](https://github.com/twilio/twilio-cli/pull/391/files#r803772497), the support for centos stream8 expired last month. Bumping the version that is supported till [2027-05-31](https://www.centos.org/cl-vs-cs/#:~:text=CentOS%20Stream%209%20EOL%3A%202027%2D05%2D31)
=> chore: upgrading to centos:stream9

package-lock.json, src/hooks/init/twilio-api.js
Adding check for undefined pathType
=> chore: adding check for undefined pathType

.github/workflows/acceptance-tests.yml, .github/workflows/macos-executable-release.yml
GitHub has removed the support for macos-11. Reference [doc](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/). 
=> chore: upgrading to macos-12 as macos-11 support is dropped

.github/workflows/macos-executable-release.yml
=> chore: update to macos-12

.github/workflows/windows-executable-release.yml
=> chore: bump download-artifact to v4

package.json
Bumping cli-core version to get this [fix](https://github.com/twilio/twilio-cli-core/pull/251). Tests will fail till cli-core version is not released 
=> chore: bump cli-core version

.github/workflows/macos-executable-release.yml
MacOS 12 is deprecated. See [here](https://github.com/twilio/twilio-cli/actions/runs/12181564229/job/33978765646)
=> chore: upgarde to macos13

.github/scripts/pack_macos.sh
base64 command is changed from --output to >
=> chore: update base64 --output flag to >

.github/workflows/acceptance-tests.yml
=> chore: upgrade to macos-13 in acceptance test

CHANGES.md
Since CLI core was manually released, need to do this change here too
=> chore: Update CHANGES.md

.github/workflows/rollback.yaml
=> chore: Create rollback.yaml

.github/workflows/rollback.yaml
=> chore: Update rollback.yaml

.github/scripts/update-cli-core-release-version.js, .github/workflows/cli-audit.yml, .github/workflows/cli-test.yml, .github/workflows/release.yml, CHANGES.md, package-lock.json, package.json
1. Updated setup-node version
2. Added cli-core mapping
=> chore: release test

README.md
Update readme for node 18 deprecation and node 20 support
=> feat!: Node 18 is no longer supported from version 6.0.0. Please upgrade to Node 20 or above

README.md
=> chore: Upgrade guide node 20

package-lock.json, package.json
Resolving transitive dependency of tar-fas which has the following security vulnerability - https://security.snyk.io/vuln/SNYK-JS-TARFS-10293725
This is coming from ocli/plugin-update which upgraded this dependency in v4.6.42. See [here](https://github.com/oclif/plugin-update/pull/1111).
=> chore: update oclif/plugin-update

.github/workflows/acceptance-tests.yml
Acceptance test for scoop started failing with 7Zip version 25.01. Pinning to last stable version of 25.00
=> chore: pin stable version of 7zip for scoop testing
